### ISSUE TITLE
Add Windows backend

### ISSUE THREAD

**Issue by olokobayusuf** [natmlx/NatReader#4]

**Comment by dsmtE** [comment]
Hello,
I would like to use natReader on windows. When do you plan to integrate it ?

Thanks in advance.

**Comment by olokobayusuf** [comment]
Hey @dsmtE there's no ETA yet, NatReader is somewhat of a low-priority project, an addendum to the NatCorder platform.

**Comment by olokobayusuf** [comment]
Implemented in [NatML](https://github.com/natmlx/NatML).
